In [22]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
import pandas as pd

In [23]:
obj=LabelEncoder()
obj1=OneHotEncoder(sparse_output=False)

In [24]:
df=pd.DataFrame({'Gender':['m','m','f','m','f']})

In [6]:
df['Gender']=obj.fit_transform(df['Gender'])

In [7]:
df

   Gender
0       1
1       1
2       0
3       1
4       0

In [17]:
df1=pd.DataFrame({'product':['mouse','moniter','machine','motor','keyboard','laptop','television','projector']})

In [19]:
df1['product']=obj.fit_transform(df1['product'])

In [20]:
df1

   product
0        5
1        3
2        2
3        4
4        0
5        1
6        7
7        6

In [28]:
obj1=OneHotEncoder(sparse_output=False)
data=obj1.fit_transform(df)
col=obj1.get_feature_names_out()
df=pd.DataFrame(data,columns=col)
df

   Gender_f  Gender_m
0       0.0       1.0
1       0.0       1.0
2       1.0       0.0
3       0.0       1.0
4       1.0       0.0